"""initial schema

Revision ID: b79e66d05c95
Revises: 
Create Date: 2026-09-20 17:52:14.745890

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b79e66d05c95'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('phone_hash', sa.String(length=64), nullable=True),
    sa.Column('niche', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=8), server_default='uz', nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('trial_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('balance_units', sa.Integer(), server_default='0', nullable=False),
    sa.Column('referral_code', sa.String(length=16), nullable=False),
    sa.Column('referred_by', sa.Uuid(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('balance_units >= 0', name=op.f('ck_users_balance_non_negative')),
    sa.ForeignKeyConstraint(['referred_by'], ['users.id'], name=op.f('fk_users_referred_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('phone_hash', name=op.f('uq_users_phone_hash')),
    sa.UniqueConstraint('referral_code', name=op.f('uq_users_referral_code')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_users_telegram_id'))
    )
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_code', sa.String(length=32), nullable=False),
    sa.Column('amount_uzs', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('manual', 'payme', 'click', name='paymentprovider', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='paymentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('receipt_file_id', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_payments_decided_by_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('uploads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('blob_path', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('INIT', 'UPLOADED', 'VERIFIED', 'REJECTED', 'EXPIRED', name='uploadstatus', native_enum=False, length=32), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('has_audio', sa.Boolean(), nullable=True),
    sa.Column('video_codec', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_uploads_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploads'))
    )
    op.create_index(op.f('ix_uploads_user_id'), 'uploads', ['user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('upload_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'AWAITING_CONFIRM', 'QUEUED', 'PREPROCESSING', 'ANALYZING', 'PLANNING', 'AWAITING_PLAN_APPROVAL', 'REVISING', 'RENDERING', 'DELIVERING', 'DONE', 'FAILED', 'CANCELED', 'EXPIRED', name='jobstatus', native_enum=False, length=32), nullable=False),
    sa.Column('is_trial', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('aspect', sa.String(length=16), nullable=True),
    sa.Column('style_preset', sa.String(length=64), nullable=True),
    sa.Column('brief', sa.Text(), nullable=True),
    sa.Column('units_cost', sa.Integer(), server_default='0', nullable=False),
    sa.Column('revision_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('current_plan_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status_message_id', sa.BigInteger(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('output_blob_path', sa.Text(), nullable=True),
    sa.Column('output_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stt_seconds', sa.Float(), server_default='0', nullable=False),
    sa.Column('llm_input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('llm_output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('render_seconds', sa.Float(), server_default='0', nullable=False),
    sa.Column('est_cost_usd', sa.Numeric(precision=12, scale=4), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], name=op.f('fk_jobs_upload_id_uploads')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_jobs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index('ix_jobs_status_updated_at', 'jobs', ['status', 'updated_at'], unique=False)
    op.create_index('ix_jobs_user_id_status', 'jobs', ['user_id', 'status'], unique=False)
    op.create_table('edit_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('plan_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('human_summary', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('ai_initial', 'ai_revision', 'fallback', name='plansource', native_enum=False, length=32), nullable=False),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_edit_plans_job_id_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_edit_plans')),
    sa.UniqueConstraint('job_id', 'version', name='uq_edit_plans_job_id_version')
    )
    op.create_table('unit_ledger',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('purchase', 'reserve', 'refund', 'revision', 'referral', 'admin_grant', name='ledgerreason', native_enum=False, length=32), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('payment_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('delta <> 0', name=op.f('ck_unit_ledger_delta_non_zero')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_unit_ledger_job_id_jobs')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_unit_ledger_payment_id_payments')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_unit_ledger_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unit_ledger'))
    )
    op.create_index('ix_unit_ledger_job_id', 'unit_ledger', ['job_id'], unique=False)
    op.create_index('ix_unit_ledger_user_id_created_at', 'unit_ledger', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unit_ledger_user_id_created_at', table_name='unit_ledger')
    op.drop_index('ix_unit_ledger_job_id', table_name='unit_ledger')
    op.drop_table('unit_ledger')
    op.drop_table('edit_plans')
    op.drop_index('ix_jobs_user_id_status', table_name='jobs')
    op.drop_index('ix_jobs_status_updated_at', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_uploads_user_id'), table_name='uploads')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('users')
    # ### end Alembic commands ###
