"""payment note

Revision ID: d6a6c4083440
Revises: b79e66d05c95
Create Date: 2026-09-21 18:01:18.354406

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd6a6c4083440'
down_revision: str | None = 'b79e66d05c95'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'note')
    # ### end Alembic commands ###
